import keyMirror from 'key-mirror'

const ASSESSMENT_WIZARD = keyMirror({
  ADD_CARD: null,
  ADD_CARD_SUCCESS: null,
  ADD_CARD_FAILURE: null,
  REMOVE_CARD: null,
  REMOVE_CARD_SUCCESS: null,
  REMOVE_CARD_FAILURE: null,
  ASSESSMENT_INITIALIZE_HASHES_LOOKUP: null,
  ASSESSMENT_NEXT_STEP: null,
  ASSESSMENT_PREVIOUS_STEP: null,
  ASSESSMENT_ON_EXTERNAL_URL_CHANGE: null,
  SUBMIT_ANONYMOUS_MEMBER: null,
  GET_MEMBER: null,
  GET_ALL_MEMBERS_SUCCESS: null,
  GET_ALL_MEMBERS_FAILURE: null,
  GET_MEMBER_SUCCESS: null,
  GET_MEMBER_FAILURE: null,
  UPDATE_MEMBER: null,
  UPDATE_MEMBER_SUCCESS: null,
  UPDATE_MEMBER_FAILURE: null,
  CREATE_EMPTY_USER_AND_MEMBER_SUCCESS: null,
  CREATE_EMPTY_USER_AND_MEMBER_FAILURE: null,
  CREATE_STATE_SUCCESS: null,
  CREATE_STATE_FAILURE: null,
  UPDATE_STATE_SUCCESS: null,
  UPDATE_STATE_FAILURE: null,
  GET_STATE_SUCCESS: null,
  GET_STATE_FAILURE: null
})

export default ASSESSMENT_WIZARD
