import keyMirror from 'key-mirror'

const DESTINATIONS = keyMirror({
  SUBMIT_DESTINATIONS_LIST: null,
  ON_DESTINATIONS_LIST_SUBMIT_SUCCESS: null,
  ON_DESTINATIONS_LIST_SUBMIT_FAILURE: null,
  OPEN_FIRST_DESTINATION_SELECT_MODAL: null,
  CLOSE_FIRST_DESTINATION_SELECT_MODAL: null,
  CLOSE_SUGGESTED_PATHS_DISCLAIMER_MODAL: null,
  OPEN_SUGGESTED_PATHS_DISCLAIMER_MODAL: null,
  OPEN_CONFIRM_PATH_REMOVE_MODAL: null,
  CLOSE_CONFIRM_PATH_REMOVE_MODAL: null,
  SELECT_PATH: null,
  REMOVE_PATH: null,
  ON_REMOVE_PATH_SUCCESS: null,
  ON_REMOVE_PATH_FAILURE: null,
  PRESELECT_PATHS: null,
  SUBMIT_PATHS_LIST: null,
  ON_PATHS_LIST_SUBMIT_SUCCESS: null,
  ON_PATHS_LIST_SUBMIT_FAILURE: null
})

export default DESTINATIONS
