import keyMirror from 'key-mirror'

const REGISTRATION_WIZARD = keyMirror({
  REGISTRATION_INITIALIZE_HASHES_LOOKUP: null,
  REGISTRATION_NEXT_STEP: null,
  REGISTRATION_PREVIOUS_STEP: null,
  REGISTRATION_ON_EXTERNAL_URL_CHANGE: null
})

export default REGISTRATION_WIZARD
